# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  shared-network:
    driver: bridge

services:

  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin:2.11
    ports:
      - 9411:9411

  # This sidecar publishes metrics to the console by default.
  metrics:
    container_name: metrics
    networks:
      - shared-network
    image: gcr.io/${PROJECT}/metrics-amd64:1.0
    ports:
      - 3001:3001 # EXPVAR API
      - 4001:4001 # DEBUG API

  # This starts a local PostgreSQL DB.
  db:
    container_name: api_db
    networks:
      - shared-network
    image: postgres:11.1-alpine
    ports:
      - 5432:5432

  # This is the core CRUD based service.
  getlive-api:
    container_name: getlive-api
    networks:
      - shared-network
    image: gcr.io/${PROJECT}/getlive-api-amd64:1.0
    ports:
      - 3000:3000 # CRUD API
      - 4000:4000 # DEBUG API
    environment:
      - API_DB_HOST=db
      - API_DB_DISABLE_TLS=1 # This is only disabled for our development enviroment.
      - API_TWITTER_CONSUMER_KEY=${API_TWITTER_CONSUMER_KEY}
      - API_TWITTER_CONSUMER_SECRET=${API_TWITTER_CONSUMER_SECRET}
      - API_TWITTER_ACCESS_TOKEN=${API_TWITTER_ACCESS_TOKEN}
      - API_TWITTER_ACCESS_SECRET=${API_TWITTER_ACCES_SECRET}
      - API_TWITTER_TOPICS=#TogetherAtHome;#StayHome;#QuarantineandChill;#ClubQuarantine;#VirtualFitness;#Quarantoned;#BigOnlinePar;#WatchParty;#LockDownNow;#StayHomeStaySafe;#Quarantined;#GetLiveTesting
      - API_AGGREGATOR_YOUTUBE_API_KEY=${API_AGGREGATOR_YOUTUBE_API_KEY}
      # - GODEBUG=gctrace=1
    depends_on:
      - metrics
      - zipkin
      - db
