apiVersion: apps/v1
kind: Deployment
metadata:
  name: getlive-api
spec:
  selector:
    matchLabels:
      app: getlive-api
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: getlive-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.11
        ports:
        - name: zipkin
          containerPort: 9411
        resources: {}
      - name: getlive-api
        image: gcr.io/getlive-backend-api/getlive-api-amd64:1.0
        env:
        - name: API_DB_HOST
          value: 0.0.0.0
        - name: API_DB_DISABLE_TLS
          value: "true"
        ports:
        - name: getlive-api
          containerPort: 3000
        - name: debug
          containerPort: 4000
        resources: {}
      - name: metrics
        image: gcr.io/getlive-backend-api/metrics-amd64:1.0
        env:
        - name: METRICS_COLLECT_FROM
          value: "http://localhost:4000/debug/vars"
        ports:
        - name: metrics
          containerPort: 3001
        - name: debug
          containerPort: 4001
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: getlive-api
spec:
  selector:
    service: getlive-api
  ports:
  - name: "zipkin"
    port: 9411
    targetPort: 9411
  - name: "getlive-api"
    port: 3000
    targetPort: 3000
  - name: "getlive-api-debug"
    port: 4000
    targetPort: 4000
  - name: "metrics"
    port: 3001
    targetPort: 3001
  - name: "metrics-debug"
    port: 4001
    targetPort: 4001
